-- for `vim.keymap.set`, `noremap=true` is default, thus do not explicitly set it.

---[Strudel]----------------------------------------------------------------------------------------------------
--local strudel = require("strudel")

--vim.keymap.set("n", "<leader>sl", strudel.launch, { desc = "Launch Strudel" })
--vim.keymap.set("n", "<leader>sq", strudel.quit, { desc = "Quit Strudel" })
--vim.keymap.set("n", "<leader>st", strudel.toggle, { desc = "Strudel Toggle Play/Stop" })
--vim.keymap.set("n", "<leader>su", strudel.update, { desc = "Strudel Update" })
--vim.keymap.set("n", "<leader>ss", strudel.stop, { desc = "Strudel Stop Playback" })
--vim.keymap.set("n", "<leader>sb", strudel.set_buffer, { desc = "Strudel set current buffer" })
--vim.keymap.set("n", "<leader>sx", strudel.execute, { desc = "Strudel set current buffer and update" })

-- ---[nvim-Telescope]---------------------------------------------------------------------------------------------
-- { "<leader>ff", "<cmd>Telescope find_files<cr>",                    desc = "Find Files" },
-- local builtin = require("telescope.builtin")
--
-- vim.keymap.set("n", "<leader>ff", builtin.find_files, { silent = true, desc = "Telescope::find_files" })
--
--
-- local builtin = require("telescope.builtin")
--
-- vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "Find Files" })
-- vim.keymap.set("n", "<leader>fg", builtin.git_files,  { desc = "Find Git Files" })
-- vim.keymap.set("n", "<leader>fb", builtin.buffers,    { desc = "Find Buffers" })
-- vim.keymap.set("n", "<leader>/",  builtin.live_grep,  { desc = "Grep Content" })
-- vim.keymap.set("n", "<leader>fh", builtin.help_tags,  { desc = "Help Pages" })
-- vim.keymap.set("n", "<leader>fk", builtin.keymaps,    { desc = "Keymaps" })
-- vim.keymap.set("n", "<leader>fc", function()
--     builtin.find_files({ cwd = "~/.config/nvim" })
-- end, { desc = "Find Config" })
